from lumigo_tracer.event.trigger_parsing.step_function_parser import StepFunctionEventTriggerParser
from lumigo_core.triggers.trigger_parsing import EVENT_TRIGGER_PARSERS


EVENT_TRIGGER_PARSERS.append(StepFunctionEventTriggerParser)
